In [ ]:
#NumPy is a Python library used for working with arrays.
#It also has functions for working in domain of linear algebra, fourier transform, and matrices.
#NumPy was created in 2005 by Travis Oliphant
#NumPy stands for Numerical Python.
#NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [1]:
pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ---------------------------------------- 59.7/59.7 kB 1.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.2/12.9 MB 4.8 MB/s eta 0:00:03
    --------------------------------------- 0.3/12.9 MB 3.6 MB/s eta 0:00:04
   - -------------------------------------- 0.4/12.9 MB 3.4 MB/s eta 0:00:04
   - -------------------------------------- 0.6/12.9 MB 3.2 MB/s eta 0:00:04
   -- ------------------------------------- 0.7/12.9 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 0.9/12.9 MB 3.2 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/12.9 MB 3.8 MB/s eta 0:00:04
   ----- ---------------------------------- 1.7/12.9 MB 4.3 MB/s eta 0:00:03
   ------ --------------------------------- 2.0/12.9 MB 4.7 MB/s eta 0:00:03
   ------ --------------------------------- 2.0/12.9 MB 4.7 MB/s eta 0:00:03
   -----

In [3]:
import numpy as np

In [6]:
np.array([1,2,3,5,8])

array([1, 2, 3, 5, 8])

In [8]:
np.array([1,2,3,5,8],dtype=str)

array(['1', '2', '3', '5', '8'], dtype='<U1')

In [11]:
#2D array
np.array([[1,2,3,5,8],[2,8,6,3,5]])

array([[1, 2, 3, 5, 8],
       [2, 8, 6, 3, 5]])

In [14]:
b=np.array([[1,2,3,5,8],[2,8,6,3,5],[5,8,9,6,3]])
print(b)

[[1 2 3 5 8]
 [2 8 6 3 5]
 [5 8 9 6 3]]


In [15]:
type(b)

numpy.ndarray

In [16]:
#assecs the element of of array
b[2,3] #[row no,col no]


np.int64(6)

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
np.ones((5,6))+2200

array([[2201., 2201., 2201., 2201., 2201., 2201.],
       [2201., 2201., 2201., 2201., 2201., 2201.],
       [2201., 2201., 2201., 2201., 2201., 2201.],
       [2201., 2201., 2201., 2201., 2201., 2201.],
       [2201., 2201., 2201., 2201., 2201., 2201.]])

In [25]:
#Random number
np.random.rand(2,3)

array([[0.25137128, 0.29372306, 0.2517432 ],
       [0.92471622, 0.41321571, 0.45703845]])

In [28]:
a=np.round(np.random.rand(2,3),decimals=2)
print(a)

[[0.58 0.84 0.51]
 [0.41 0.96 0.22]]


In [30]:
np.random.randint(50,100,(2,4)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

array([[56, 62, 62, 59],
       [72, 52, 88, 76]], dtype=int32)

In [32]:
np.full((2,3),125)

array([[125, 125, 125],
       [125, 125, 125]])

In [34]:
# identity matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
# not an identity matrix
np.eye(6,k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [41]:
#range() only for integer
#arange() both integer and float
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [43]:
np.arange(0.5,10.0,0.3) #it accepts float values as well

array([0.5, 0.8, 1.1, 1.4, 1.7, 2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1,
       4.4, 4.7, 5. , 5.3, 5.6, 5.9, 6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. ,
       8.3, 8.6, 8.9, 9.2, 9.5, 9.8])