In [1]:
import numpy as np

In [8]:
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# append values to ndarray
a=np.array([[1,2],[3,4]])
print(a)
b=np.append(a,[[5],[6]],axis=1)#using append function adding col
print("using append function adding coloumn""\n",b)
b=np.append(a,[[5,6]],axis=0)#using append function adding row
print("using append function adding row","\n",b)

[[1 2]
 [3 4]]
using append function adding coloumn
 [[1 2 5]
 [3 4 6]]
using append function adding row 
 [[1 2]
 [3 4]
 [5 6]]


In [17]:
a=np.arange(10,20,2)
b=np.array([[2],[3]])
print(a)
print(b)
print('Adding two different size arrays :','\n',a+b)
print('Multiplying an ndarray and a number :',a*2)

[10 12 14 16 18]
[[2]
 [3]]
Adding two different size arrays : 
 [[12 14 16 18 20]
 [13 15 17 19 21]]
Multiplying an ndarray and a number : [20 24 28 32 36]


In [18]:
a=np.ones((3,3))
print(a)
b=np.array([2])
print(b)
print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [21]:
a=np.ones((5,5))
b=np.array([5])
print(a+b)

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [22]:
a=np.array([1,2,3,4,5,6])
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [-4 -3 -2 -1  0  1]
Multiply : [ 5 10 15 20 25 30]
Divide : [0.2 0.4 0.6 0.8 1.  1.2]
Power : [ 1  4  9 16 25 36]
Remainder : [1 2 3 4 0 1]


In [23]:
a = np.arange(5,15,2)
print(a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

[ 5  7  9 11 13]
Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [25]:
l=np.array([[1,2,3],[4,5,6]])


In [26]:
o=np.array([[2,2,4],[6,8,9]])

In [27]:
l+o

array([[ 3,  4,  7],
       [10, 13, 15]])

In [28]:
u=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype = float)
print(u)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [29]:
u>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [30]:
u[u>5]

array([ 6.,  7.,  8.,  9., 10., 11., 12.])

In [31]:
a = np.array([[1,6,5],[4,3,7]])
print(a)
# minimum along a row
print('Min :',np.min(a,axis=1))
# maximum along a column
print('Max :',np.max(a,axis=0))

[[1 6 5]
 [4 3 7]]
Min : [1 3]
Max : [4 6 7]


In [32]:
array=np.arange(12).reshape(3,4)
print("INPUT ARRAY : \n", array)
print("\nIndices of Max element : ", np.argmax(array, axis=0))
print("\nIndices of Max element : ", np.argmax(array, axis=1))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Indices of Max element :  [2 2 2 2]

Indices of Max element :  [3 3 3]


In [33]:
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY : \n", array)
# as per the indices
print("\nIndices of Min element : ", np.argmin(array, axis=0))
print("\nIndices of Min element : ", np.argmin(array, axis=1))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Indices of Min element :  [0 0 0 0]

Indices of Min element :  [0 0 0]


In [34]:
mat1 = np.array(np.random.randint(1,10,9)).reshape(3,3)#Creating random Numpy array of size 3x3

In [35]:
mat1

array([[1, 5, 2],
       [6, 8, 2],
       [2, 6, 2]], dtype=int32)

In [37]:
np.min(mat1)

np.int32(1)

In [38]:
np.max(mat1)

np.int32(8)

In [39]:
np.sqrt(mat1)

array([[1.        , 2.23606798, 1.41421356],
       [2.44948974, 2.82842712, 1.41421356],
       [1.41421356, 2.44948974, 1.41421356]])

In [40]:
np.mean(mat1)

np.float64(3.7777777777777777)

In [41]:
np.median(mat1)

np.float64(2.0)

In [42]:
np.var(mat1)

np.float64(5.506172839506173)

TypeError: std() got an unexpected keyword argument 'rounds'