In [ ]:
#Indexing and Slicing of NumPy array
#So far, we have seen how to create a NumPy array and how to play around with its shape. 
#In this section, we will see how to extract specific values from the array using indexing and slicing.
#Slicing means retrieving elements from one index to another index.

In [1]:
import numpy as np

In [4]:
#[start:End:step]
a=np.array([1,2,3,4,5,6,5,8,5,6,7])
print(a[2:6:3])

[3 6]


In [5]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a[1:12:2])

[ 2  4  6  8 10 12]


In [6]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#do not pass start
print(a[:6:3])
#do not pass end
print(a[1::2])
##do not pass step
print(a[1:6:])

[1 4]
[ 2  4  6  8 10 12]
[2 3 4 5 6]


In [7]:
a=np.array([[1,2,3],[4,5,6]])
print(a[0,0])
print(a[1,2])
print(a[1,0])

1
6
4


In [ ]:
#Slicing 2D NumPy arrays
#To slice a 2-D array,you need to mention the slices for both, the row and the column.

In [8]:
a=np.array([[1,2,3,9],[4,5,6,8],[7,8,9,7],[7,8,9,11]])
# print first row values
#[row:col]
print(' 2DArray :','\n',a)
print('First row values :','\n',a[1:3,0:3])

 2DArray : 
 [[ 1  2  3  9]
 [ 4  5  6  8]
 [ 7  8  9  7]
 [ 7  8  9 11]]
First row values : 
 [[4 5 6]
 [7 8 9]]


In [15]:
#2D array
a=np.array([[1,2,3,9],[4,5,6,8],[7,8,9,7],[7,8,9,11]])
print("Second row value:",a[2:3,0:3])

Second row value: [[7 8 9]]


In [16]:
print(' 2DArray :','\n',a)
print('Second column values :','\n',a[:,1:])

 2DArray : 
 [[ 1  2  3  9]
 [ 4  5  6  8]
 [ 7  8  9  7]
 [ 7  8  9 11]]
Second column values : 
 [[ 2  3  9]
 [ 5  6  8]
 [ 8  9  7]
 [ 8  9 11]]


In [17]:
print(' 2DArray :','\n',a)
# with step-size for columns
print('Alternate values from first row:','\n',a[0:3,::2])

 2DArray : 
 [[ 1  2  3  9]
 [ 4  5  6  8]
 [ 7  8  9  7]
 [ 7  8  9 11]]
Alternate values from first row: 
 [[1 3]
 [4 6]
 [7 9]]


In [18]:
print('Arbitrary values :','\n',a[0:1,2:3])

Arbitrary values : 
 [[3]]


In [19]:
#Negative slicing prints elements from the end rather than the beginning
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a[::-1,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [20]:
a=np.array([[ 1,2,3,4,5,8],[6,7,8,9,10,78],[16,17,18,19,110,76], [116,117,118,119,1110,176], [1116,1117,1118,1119,110,1176]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])

Original array : 
 [[   1    2    3    4    5    8]
 [   6    7    8    9   10   78]
 [  16   17   18   19  110   76]
 [ 116  117  118  119 1110  176]
 [1116 1117 1118 1119  110 1176]]
Reversed array : 
 [[1176  110 1119 1118 1117 1116]
 [ 176 1110  119  118  117  116]
 [  76  110   19   18   17   16]
 [  78   10    9    8    7    6]
 [   8    5    4    3    2    1]]


In [28]:
v=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Original v:","\n",a)
print("Reversed v:","\n",a[1::2,::-2])

Original v: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed v: 
 [[10  8  6]]


In [21]:
#flip() method to reverse an ndarray.
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array vertically :','\n',np.flip(a,axis=1))
print('Reversed array horizontally :','\n',np.flip(a,axis=0))

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array vertically : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
Reversed array horizontally : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [37]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("original","\n",a)
c=np.flip(a,axis=0)#for row flip
print("for row:","\n",c)
b=np.flip(a,axis=1)#for col flip
print("for col:","\n",b)

original 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
for row: 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
for col: 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]


In [38]:
#Stacking ndarrays
#You can create a new array by combining existing arrays. This you can do in two ways:
#Either combine the arrays vertically (i.e. along the rows) using the vstack() method, thereby increasing the number of rows in the resulting array
#Or
#combine the arrays in a horizontal fashion (i.e. along the columns) using the hstack(), thereby increasing the number of columns in the resultant array
a=np.arange(0,5)
b=np.arange(5,10)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))#stack for row
print('Horizontal stacking :','\n',np.hstack((a,b)))#stck for col

Array 1 : 
 [0 1 2 3 4]
Array 2 : 
 [5 6 7 8 9]
Vertical stacking : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stacking : 
 [0 1 2 3 4 5 6 7 8 9]


In [39]:
#order are important
a=np.arange(0,4)
b=np.arange(5,9)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))
print('Horizontal stacking :','\n',np.hstack((a,b)))

Array 1 : 
 [0 1 2 3]
Array 2 : 
 [5 6 7 8]
Vertical stacking : 
 [[0 1 2 3]
 [5 6 7 8]]
Horizontal stacking : 
 [0 1 2 3 5 6 7 8]
