In [2]:
import numpy as np

In [10]:
a=np.array([[5,10,15,6],[20,25,30,0]])
print('Size of array :',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])
print("Number of row and column:",a.shape[0],a.shape[1])

Size of array : 8
Manual determination of size of array : 8
Number of row and column: 2 4


In [13]:
a=np.array([5,10,15,25])
k=a.shape
print(k)
type(a)

(4,)


numpy.ndarray

In [18]:
# reshape
a=np.array([3,6,9,12,23,55,25,86])
print(a)
np.reshape(a,(2,4))# reshaped the ndarray from a 1-D to a 2-D ndarray.

[ 3  6  9 12 23 55 25 86]


array([[ 3,  6,  9, 12],
       [23, 55, 25, 86]])

In [19]:
a=np.array([3,6,9,12,18,24,19,56])
print('Three rows :','\n',np.reshape(a,(2,-1)))

Three rows : 
 [[ 3  6  9 12]
 [18 24 19 56]]


In [24]:
a=np.array([3,6,9,12,18,24,19,56])
print('Three rows :','\n',np.reshape(a,(2,-2)))

Three rows : 
 [[ 3  6  9 12]
 [18 24 19 56]]


In [26]:
print('Three columns :','\n',np.reshape(a,(-2,2)))

Three columns : 
 [[ 3  6]
 [ 9 12]
 [18 24]
 [19 56]]


In [28]:
a = np.ones((2,3))
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

Original shape : (2, 3)
Array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
Shape after flatten : (6,)
Array : 
 [1. 1. 1. 1. 1. 1.]
Shape after ravel : (6,)
Array : 
 [1. 1. 1. 1. 1. 1.]


In [31]:
a=np.array([[3,6,9,12],[18,24,19,56]])
print(a)

[[ 3  6  9 12]
 [18 24 19 56]]


In [32]:
a.flatten()

array([ 3,  6,  9, 12, 18, 24, 19, 56])

In [34]:
b=np.array([[2,3,4,5,6],[5,8,9,6,3]])
print(b)

[[2 3 4 5 6]
 [5 8 9 6 3]]


In [35]:
b.flatten()

array([2, 3, 4, 5, 6, 5, 8, 9, 6, 3])

In [36]:
b[0]=0# deep copy
print(a)

[[ 3  6  9 12]
 [18 24 19 56]]


In [37]:
c[0]=0# shallow copy
print(a)

[[ 3  6  9 12]
 [18 24 19 56]]


In [39]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [40]:
c=a

IndexError: list assignment index out of range

In [43]:
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)
print('Original','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
Expand along columns: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


In [44]:
# expand dimensions
a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)#expand row
c = np.expand_dims(a,axis=1)#expand col
print('Original:','\n','Shape',a.shape,'\n',a)
print('Expand along rows:','\n','Shape',b.shape,'\n',b)
print('Expand along columns:','\n','Shape',c.shape,'\n',c)

Original: 
 Shape (3,) 
 [1 2 3]
Expand along rows: 
 Shape (1, 3) 
 [[1 2 3]]
Expand along columns: 
 Shape (3, 1) 
 [[1]
 [2]
 [3]]


In [45]:

a=np.array([[[1,2,3],[4,5,6]]])
b=np.squeeze(a, axis=0)#minimize dimension
print('Original','\n','Shape',a.shape,'\n',a)
print('Squeeze array:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (1, 2, 3) 
 [[[1 2 3]
  [4 5 6]]]
Squeeze array: 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
